// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVsxVWuCGAa3P2Z1_QQunl0lW4APuXI8',
    appId: '1:341507104869:web:41d784e88ef6059a60e68c',
    messagingSenderId: '341507104869',
    projectId: 'testmyapplication-c1acb',
    authDomain: 'testmyapplication-c1acb.firebaseapp.com',
    storageBucket: 'testmyapplication-c1acb.appspot.com',
    measurementId: 'G-35T65DNZMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Y0ReIqpABrU2OGCTHdMnvevsnW_G6I0',
    appId: '1:341507104869:android:5add1e2c48360dad60e68c',
    messagingSenderId: '341507104869',
    projectId: 'testmyapplication-c1acb',
    storageBucket: 'testmyapplication-c1acb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3J9E83xSlUKwkSNz3T13E-hiAhU0K-E',
    appId: '1:341507104869:ios:3a0eab653da59af460e68c',
    messagingSenderId: '341507104869',
    projectId: 'testmyapplication-c1acb',
    storageBucket: 'testmyapplication-c1acb.appspot.com',
    iosBundleId: 'com.example.untitled13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3J9E83xSlUKwkSNz3T13E-hiAhU0K-E',
    appId: '1:341507104869:ios:9e7eb141ed10a07e60e68c',
    messagingSenderId: '341507104869',
    projectId: 'testmyapplication-c1acb',
    storageBucket: 'testmyapplication-c1acb.appspot.com',
    iosBundleId: 'com.example.untitled13.RunnerTests',
  );
}
